ipa: neo: stats: Fix unused parameter build error
A build error due to unused parameter was introduced in
commit b78cf8ac73acdcb244748f791124c40bcefdf187

This patch fixes this error which was generated as:
../src/ipa/nxp/neo/stats.cpp:64:59: error: unused parameter ‘type’ [-Werror=unused-parameter]
   64 |                                            BlockStatsType type, const Span<uint8_t> &data)

Fixes:  b78cf8ac73ac ("ipa: nxp: stats: Remove unused member variables")
Signed-off-by: Celine Laurencin <celine.laurencin@nxp.com>